Week17_NetworkDBProject_05052016/Models/vwRatingsAbove4.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week17_NetworkDBProject_05052016.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRatingsAbove4
    {
        public int ShowID { get; set; }
        public int NetworkID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Photo { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
    }
}

Week17_NetworkDBProject_05052016/Controllers/ShowsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Week17_NetworkDBProject_05052016.Models;

namespace Week17_NetworkDBProject_05052016.Controllers
{
    public class ShowsController : Controller
    {
        private TVNetworkShowsDBEntities db = new TVNetworkShowsDBEntities();

        // GET: Shows
        public ActionResult Index(int? network, string sortBy)
        {
            if (network == 0)
            {
                //return View(db.Shows.OrderBy(x => x.Title).Where(x => x.NetworkID == network).ToList());
                var shows = db.Shows.Include(s => s.Network);
                return View(shows.OrderBy(x => x.Title).ToList());

            }
            else if (network >= 1)
            {
                return View(db.Shows.OrderBy(x => x.Title).Where(x => x.NetworkID == network).ToList());
            }
            else
            {
                var shows = db.Shows.Include(s => s.Network);
                switch (sortBy)
                {
                    case "Title":
                        return View(shows.OrderBy(x => x.Title).ToList());
                    case "Genre":
                        return View(shows.OrderBy(x => x.Genre).ToList());
                    case "Rating":
                        return View(shows.OrderBy(x => x.Rating).ToList());
                    case "Network":
                        return View(shows.OrderBy(x => x.Network.Name).ToList());
                    default:
                        return View(shows.OrderBy(x => x.Title).ToList());
                }
            }
        }

        public ActionResult Filter(string filterBy, int? network)
        {
            ViewBag.Message = filterBy;
            switch(filterBy)
            {
                case "Network":
                    return View(db.Shows.OrderBy(x => x.Title).Where(x => x.NetworkID == network).ToList());
                    break;
                //case "Genre":
                //    return View();
                //    break;
                //case "Rating":
                //    return View();
                //    break;
                case "Comedy":
                    return View(db.Shows.OrderBy(x => x.Title).Where(x => x.Genre == "Comedy").ToList());
                    break;
                case "Drama":
                    return View(db.Shows.OrderBy(x => x.Title).Where(x => x.Genre == "Drama").ToList());
                    break;
                default:
                    return View(db.Shows.OrderBy(x => x.Title).Where(x => x.Title.Contains(filterBy)).ToList());
                    break;
            }
        }

        // I did not use this
        //public ActionResult GenreIndex ()
        //{
        //    return View(db.Shows.OrderBy(n => n.Genre).ToList());
        //}

        // I did not use this
        //public ActionResult Sort(string sortBy)
        //{
        //    var shows = db.Shows.Include(s => s.Network);
        //    return View(shows.OrderBy(x => x.Title).ToList());
        //}


        /* WHere did this come from??
        private ActionResult View(object p)
        {
            throw new NotImplementedException();
        }*/

        // GET: Shows/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Show show = db.Shows.Find(id);
            if (show == null)
            {
                return HttpNotFound();
            }
            return View(show);
        }

        // GET: Shows/Create
        public ActionResult Create()
        {
            ViewBag.NetworkID = new SelectList(db.Networks, "NetworkID", "Name");
            return View();
        }

        // POST: Shows/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ShowID,NetworkID,Title,Genre,Rating,Photo,Website,Description")] Show show)
        {
            if (ModelState.IsValid)
            {
                db.Shows.Add(show);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.NetworkID = new SelectList(db.Networks, "NetworkID", "Name", show.NetworkID);
            return View(show);
        }

        // GET: Shows/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Show show = db.Shows.Find(id);
            if (show == null)
            {
                return HttpNotFound();
            }
            ViewBag.NetworkID = new SelectList(db.Networks, "NetworkID", "Name", show.NetworkID);
            return View(show);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShowID,NetworkID,Title,Genre,Rating,Photo,Website,Description")] Show show)
        {
            if (ModelState.IsValid)
            {
                db.Entry(show).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.NetworkID = new SelectList(db.Networks, "NetworkID", "Name", show.NetworkID);
            return View(show);
        }

        // GET: Shows/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Show show = db.Shows.Find(id);
            if (show == null)
            {
                return HttpNotFound();
            }
            return View(show);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Show show = db.Shows.Find(id);
            db.Shows.Remove(show);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Week17_NetworkDBProject_05052016/Controllers/vwRatingsAbove4Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Week17_NetworkDBProject_05052016.Models;

namespace Week17_NetworkDBProject_05052016.Controllers
{
    public class vwRatingsAbove4Controller : Controller
    {
        private TVNetworkShowsDBEntities1 db = new TVNetworkShowsDBEntities1();

        // GET: vwRatingsAbove4
        public ActionResult Index()
        {
            return View(db.vwRatingsAbove4.OrderBy(x => x.Title).ToList());
        }

        // GET: vwRatingsAbove4/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vwRatingsAbove4 vwRatingsAbove4 = db.vwRatingsAbove4.Find(id);
            if (vwRatingsAbove4 == null)
            {
                return HttpNotFound();
            }
            return View(vwRatingsAbove4);
        }

        // GET: vwRatingsAbove4/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: vwRatingsAbove4/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ShowID,NetworkID,Title,Genre,Rating,Photo,Website,Description")] vwRatingsAbove4 vwRatingsAbove4)
        {
            if (ModelState.IsValid)
            {
                db.vwRatingsAbove4.Add(vwRatingsAbove4);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vwRatingsAbove4);
        }

        // GET: vwRatingsAbove4/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vwRatingsAbove4 vwRatingsAbove4 = db.vwRatingsAbove4.Find(id);
            if (vwRatingsAbove4 == null)
            {
                return HttpNotFound();
            }
            return View(vwRatingsAbove4);
        }

        // POST: vwRatingsAbove4/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShowID,NetworkID,Title,Genre,Rating,Photo,Website,Description")] vwRatingsAbove4 vwRatingsAbove4)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vwRatingsAbove4).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vwRatingsAbove4);
        }

        // GET: vwRatingsAbove4/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vwRatingsAbove4 vwRatingsAbove4 = db.vwRatingsAbove4.Find(id);
            if (vwRatingsAbove4 == null)
            {
                return HttpNotFound();
            }
            return View(vwRatingsAbove4);
        }

        // POST: vwRatingsAbove4/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            vwRatingsAbove4 vwRatingsAbove4 = db.vwRatingsAbove4.Find(id);
            db.vwRatingsAbove4.Remove(vwRatingsAbove4);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Week17_NetworkDBProject_05052016/Views/vwRatingsAbove4/Create.cshtml
@model Week17_NetworkDBProject_05052016.Models.vwRatingsAbove4

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>vwRatingsAbove4</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ShowID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShowID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShowID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NetworkID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NetworkID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NetworkID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Week17_NetworkDBProject_05052016/Views/vwRatingsAbove4/Delete.cshtml
@model Week17_NetworkDBProject_05052016.Models.vwRatingsAbove4

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>vwRatingsAbove4</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Week17_NetworkDBProject_05052016/Views/vwRatingsAbove4/Details.cshtml
@model Week17_NetworkDBProject_05052016.Models.vwRatingsAbove4

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>vwRatingsAbove4</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Week17_NetworkDBProject_05052016/Views/vwRatingsAbove4/Edit.cshtml
@model Week17_NetworkDBProject_05052016.Models.vwRatingsAbove4

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>vwRatingsAbove4</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ShowID)

        @Html.HiddenFor(model => model.NetworkID)

        @Html.HiddenFor(model => model.Title)

        @Html.HiddenFor(model => model.Genre)

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Week17_NetworkDBProject_05052016/Views/vwRatingsAbove4/Index.cshtml
@model IEnumerable<Week17_NetworkDBProject_05052016.Models.vwRatingsAbove4>

@{
    ViewBag.Title = "Index";
}

<h2 class="page-title">Highly Rated TV Shows</h2>

<p class="link-format">
    @Html.ActionLink("Show Me All Shows", "Index", "Shows") |
    @Html.ActionLink("Show Me Highly Rated Shows", "Index", "vwRatingsAbove4")
</p>


<!-- Users will not Add Shows
<p>
    @Html.ActionLink("Create New", "Create")
</p>
-->

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <!--
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        -->
        <th>
            @Html.DisplayNameFor(model => model.Website)
        </th>
        <th>            
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            Network
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            <div class="row">
                <!--<div class="col-xs-6 col-md-3">-->
                <div class="col-xs-10 col-md-6">
                    <a href="@Html.DisplayFor(modelItem => item.Website)" target="_blank">
                        <img src="@Html.DisplayFor(modelItem => item.Photo)" class="img-thumbnail" alt="Show Photo">
                    </a>
                </div>
            </div>
        </td>
        <!--
        <td>
            @Html.DisplayFor(modelItem => item.Photo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Website)
        </td>
        -->
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NetworkID)
        </td>
        <!-- Users will not Edit, Delete or view Details
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
        -->
    </tr>
}

</table>